- Handle logic with no internet connection
VolkovSwift/WishlistApp pull request #28
Opened 2020-09-01 16:04 UTC by VolkovSwift

Add Internet reachability
Fix UI

2020-09-04 07:56 UTC, denisappdevelopment requested changes
Let's remove orig files

2020-09-04 07:56 UTC, denisappdevelopment commented on WishlistApp/Controllers/UsersViewController.swift.orig
> +protocol UsersViewDeledate: AnyObject {
Check all .org files please

2020-09-04 07:56 UTC, denisappdevelopment commented on WishlistApp/Managers/ReachabilityManager.swift
> +//            if reachability.connection == .wifi {
Clean it please

2020-09-04 07:56 UTC, denisappdevelopment commented on WishlistApp/Utilities/UIViewController + Ext.swift
> +            newView.heightAnchor.constraint(equalToConstant: 50).isActive = true
Let's make it less high, probably 30. And let's make it slightly transparent

2020-09-04 07:56 UTC, denisappdevelopment commented on WishlistAppTests/PresentersTests/MyWishlistPresenterTests.swift
> +//    func testGetGiftsSuccess() {
Don't forget to uncomment it later

2020-09-04 08:35 UTC, VolkovSwift commented on WishlistAppTests/PresentersTests/MyWishlistPresenterTests.swift
> +//    func testGetGiftsSuccess() {
Okay, I'll remove it in new unit-tests branch

2020-09-11 08:04 UTC, denisappdevelopment approved these changes

2020-09-11 08:04 UTC, merged